language: python

python:
  - "2.7"

env:
  - TOXENV=py27-1.7.X
  - TOXENV=flake8
  - TOXENV=coverage

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls
